### ISSUE TITLE
Is kalyna thread-safe?

### ISSUE THREAD

**Issue by nifker** [kalyna-cipher/kalyna#3]
When I try to encrypt with 2 threads with a blocksize and keysize of 128bit I sometimes get a segmentation fault.
`uint64_t array[1024];`
I do it like this:
thread1 encrypts &array[0],
thread2 encrypts &array[2],
thread1 encrypts &array[4],
thread2 encrypts &array[6],
and so on...

**Comment by maxkrivich** [comment]
@nifker you trying to encrypt a message in few threads at the same time?

**Comment by nifker** [comment]
@maxkrivich I encrypt a file and read in the file as many arrays and want to encrypt them in multiple threads

**Comment by zoresvit** [comment]
@nifker A code snippet that can reproduce the issue would help.

Generally as long as each thread processes different inputs and has it's own context (`ctx` structure), it should work fine.

Just keep in mind it's only a reference implementation and not an optimized one.

**Comment by nifker** [comment]
I used only one ctx structure - I'll try it with multiple and write back.

**Comment by nifker** [comment]
using multiple ctx structures fixed the problem
