### ISSUE TITLE
Performance Issues!?

### ISSUE THREAD

**Issue by nifker** [kalyna-cipher/kalyna#4]
I have written a Rust binding and am getting only a speed of about 0,2MBps (https://gitlab.com/nifker/kalyna-rust) when using it in my application (mainly here https://gitlab.com/nifker/krypt-kalyna/blob/master/src/prog.rs#L184-193).
What could reduce its performance so immense? - I already debugged it a bit and the bottleneck is in the loop.

**Comment by nifker** [comment]
@zoresvit not any better...
What is the best performance I can get with exactly this library?

**Comment by zoresvit** [comment]
@nifker This is a very broad question that cannot be answered directly without additional information. Performance highly depends on the system, processor architecture and compiler flags.

Overall, to debug performance issues you need to benchmark and profile your specific setup.

PS: Also please note that this is a *reference* implementation for research purposes, it's not optimized for any specific processor architecture and is not designed for production use.

**Comment by zoresvit** [comment]
@nifker you can take a look at [this](https://github.com/Roman-Oliynykov/ciphers-speed) benchmark on Intel i5.

**Comment by zoresvit** [comment]
@nifker You may also be interested to look at an [optimized implementation](https://github.com/weidai11/cryptopp/blob/master/kalyna.cpp) from the [CryptoPP](https://www.cryptopp.com/) library.

**Comment by zoresvit** [comment]
@nifker CryptoPP [claims](https://github.com/weidai11/cryptopp/blob/master/kalyna.cpp#L1-L10) the implementation they ended up with proved to be the fastest, but suit yourself :smile:
